const mockMenuData = {
  40998: {
    name: "Lucky Restaurant",
    cuisines: ["Biryani", "Tandoor"],
    costForTwo: "₹300 for two",
    avgRating: 4.1,
    items: [
      {
        id: "1-1",
        name: "Chicken Biryani",
        price: "₹180",
        category: "Biryani",
      },
      { id: "1-2", name: "Mutton Biryani", price: "₹220", category: "Biryani" },
      {
        id: "1-3",
        name: "Tandoori Chicken",
        price: "₹280",
        category: "Tandoor",
      },
      { id: "1-4", name: "Chicken Tikka", price: "₹250", category: "Tandoor" },
      { id: "1-5", name: "Seekh Kebab", price: "₹200", category: "Tandoor" },
    ],
  },
  2533: {
    name: "Agra Sweets Banjara",
    cuisines: ["Sweets", "Desserts", "Chaat", "Snacks", "Beverages"],
    costForTwo: "₹250 for two",
    avgRating: 4.2,
    items: [
      { id: "2-1", name: "Gulab Jamun", price: "₹60", category: "Sweets" },
      { id: "2-2", name: "Jalebi", price: "₹50", category: "Sweets" },
      { id: "2-3", name: "Pani Puri", price: "₹40", category: "Chaat" },
      { id: "2-4", name: "Samosa", price: "₹20", category: "Snacks" },
      { id: "2-5", name: "Lassi", price: "₹80", category: "Beverages" },
      { id: "2-6", name: "Rasmalai", price: "₹90", category: "Desserts" },
    ],
  },
  1196327: {
    name: "Yummy Bee",
    cuisines: ["Cakes", "Desserts", "Bakery", "Pizzas", "Pastas", "Healthy"],
    costForTwo: "₹800 for two",
    avgRating: 4.4,
    items: [
      {
        id: "3-1",
        name: "Chocolate Truffle Cake",
        price: "₹450",
        category: "Cakes",
      },
      { id: "3-2", name: "Red Velvet Cake", price: "₹400", category: "Cakes" },
      {
        id: "3-3",
        name: "Margherita Pizza",
        price: "₹350",
        category: "Pizzas",
      },
      { id: "3-4", name: "Penne Arrabiata", price: "₹280", category: "Pastas" },
      { id: "3-5", name: "Croissant", price: "₹120", category: "Bakery" },
      { id: "3-6", name: "Fruit Salad", price: "₹150", category: "Healthy" },
    ],
  },
  29287: {
    name: "KS Bakers",
    cuisines: ["Bakery", "Pizzas", "Desserts", "Snacks", "Fast Food"],
    costForTwo: "₹250 for two",
    avgRating: 4.1,
    items: [
      { id: "4-1", name: "Veg Pizza", price: "₹200", category: "Pizzas" },
      { id: "4-2", name: "Chicken Pizza", price: "₹250", category: "Pizzas" },
      { id: "4-3", name: "Bread Loaf", price: "₹60", category: "Bakery" },
      { id: "4-4", name: "Brownie", price: "₹80", category: "Desserts" },
      { id: "4-5", name: "Veg Puff", price: "₹30", category: "Snacks" },
      { id: "4-6", name: "Burger", price: "₹120", category: "Fast Food" },
    ],
  },
  807765: {
    name: "Raju Gari Biryani",
    cuisines: ["Biryani", "Chinese"],
    costForTwo: "₹300 for two",
    avgRating: 3.7,
    items: [
      {
        id: "5-1",
        name: "Chicken Biryani",
        price: "₹160",
        category: "Biryani",
      },
      { id: "5-2", name: "Egg Biryani", price: "₹120", category: "Biryani" },
      { id: "5-3", name: "Veg Biryani", price: "₹100", category: "Biryani" },
      {
        id: "5-4",
        name: "Chicken Fried Rice",
        price: "₹150",
        category: "Chinese",
      },
      { id: "5-5", name: "Veg Noodles", price: "₹120", category: "Chinese" },
      {
        id: "5-6",
        name: "Chicken Manchurian",
        price: "₹180",
        category: "Chinese",
      },
    ],
  },
  1054178: {
    name: "Dabba & Co.",
    cuisines: ["Home food", "Indian", "Thalis"],
    costForTwo: "₹200 for two",
    avgRating: 4.1,
    items: [
      { id: "6-1", name: "Veg Thali", price: "₹120", category: "Thalis" },
      { id: "6-2", name: "Non-Veg Thali", price: "₹180", category: "Thalis" },
      { id: "6-3", name: "Dal Rice", price: "₹80", category: "Home food" },
      { id: "6-4", name: "Roti Sabzi", price: "₹70", category: "Home food" },
      { id: "6-5", name: "Khichdi", price: "₹90", category: "Home food" },
      { id: "6-6", name: "Curd Rice", price: "₹80", category: "Indian" },
    ],
  },
  1027621: {
    name: "ITC Aashirvaad Soul Creations",
    cuisines: [
      "Indian",
      "Pure Veg",
      "Healthy Food",
      "South Indian",
      "North Indian",
      "Sweets",
    ],
    costForTwo: "₹500 for two",
    avgRating: 4.5,
    items: [
      {
        id: "7-1",
        name: "Masala Dosa",
        price: "₹120",
        category: "South Indian",
      },
      {
        id: "7-2",
        name: "Idli Sambar",
        price: "₹80",
        category: "South Indian",
      },
      {
        id: "7-3",
        name: "Paneer Butter Masala",
        price: "₹220",
        category: "North Indian",
      },
      {
        id: "7-4",
        name: "Dal Makhani",
        price: "₹180",
        category: "North Indian",
      },
      {
        id: "7-5",
        name: "Quinoa Salad",
        price: "₹200",
        category: "Healthy Food",
      },
      { id: "7-6", name: "Kheer", price: "₹100", category: "Sweets" },
    ],
  },
  1030838: {
    name: "Thalaiva Biryani",
    cuisines: ["Biryani", "Mughlai", "Hyderabadi", "Kebabs", "Desserts"],
    costForTwo: "₹400 for two",
    avgRating: 4.0,
    items: [
      {
        id: "8-1",
        name: "Hyderabadi Dum Biryani",
        price: "₹280",
        category: "Biryani",
      },
      {
        id: "8-2",
        name: "Lucknowi Biryani",
        price: "₹260",
        category: "Biryani",
      },
      { id: "8-3", name: "Mutton Biryani", price: "₹320", category: "Biryani" },
      { id: "8-4", name: "Shami Kebab", price: "₹220", category: "Kebabs" },
      { id: "8-5", name: "Galouti Kebab", price: "₹250", category: "Kebabs" },
      { id: "8-6", name: "Phirni", price: "₹120", category: "Desserts" },
    ],
  },
};

export default mockMenuData;
